server:
  port: 8004
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.titos.shareplatform
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true